import React, { useMemo, useState } from "react";
import { ArrowLeft, Check, Grid3X3, Link2, Puzzle, RotateCcw, Sparkles } from "lucide-react";

type Game="hub"|"puzzle"|"sudoku"|"match3"|"links";
const games=[
  {id:"puzzle" as Game,title:"Garden Puzzle",sub:"Put the garden picture back in order.",icon:Puzzle,tone:"bg-[#fff1e4] text-[#c66f2a]"},
  {id:"sudoku" as Game,title:"Gentle Sudoku",sub:"A calm 4 × 4 number puzzle.",icon:Grid3X3,tone:"bg-[#eaf1e7] text-[#52705b]"},
  {id:"match3" as Game,title:"Flower Match",sub:"Match three flowers in a row.",icon:Sparkles,tone:"bg-[#fff1e4] text-[#c66f2a]"},
  {id:"links" as Game,title:"Garden Pairs",sub:"Find and connect matching garden symbols.",icon:Link2,tone:"bg-[#eaf1e7] text-[#52705b]"},
];

export function LeisureGames({initial="hub",onExit}:{initial?:Game;onExit:()=>void}){const [game,setGame]=useState<Game>(initial);return <div className="min-h-screen bg-[#f8f4ec] text-[#293a30]"><header className="max-w-5xl mx-auto p-5 flex items-center justify-between"><button onClick={game==="hub"?onExit:()=>setGame("hub")} className="min-h-14 px-5 rounded-full bg-white border border-[#ddd6c8] font-bold flex items-center gap-2"><ArrowLeft/>{game==="hub"?"Back to Sunny":"All games"}</button><span className="font-bold text-[#65746a]">Sunny Games</span></header><main className="max-w-5xl mx-auto px-5 pb-16">{game==="hub"?<Hub onPick={setGame}/>:game==="puzzle"?<TilePuzzle/>:game==="sudoku"?<Sudoku/>:game==="match3"?<MatchThree/>:<LinkPairs/>}</main></div>}

function Hub({onPick}:{onPick:(g:Game)=>void}){return <><section className="text-center py-8"><div className="w-24 h-24 mx-auto rounded-full bg-[#e7893c] text-white flex items-center justify-center shadow-lg"><Sparkles className="w-12 h-12"/></div><p className="uppercase tracking-[.22em] text-sm font-bold text-[#c66f2a] mt-5">Play with Sunny</p><h1 className="text-4xl sm:text-5xl font-bold mt-3">Choose something relaxing</h1><p className="text-xl text-[#617067] mt-3">No timer. Take your time and enjoy.</p></section><div className="grid sm:grid-cols-2 gap-5">{games.map(({id,title,sub,icon:Icon,tone})=><button key={id} onClick={()=>onPick(id)} className="min-h-52 bg-white rounded-[2rem] border border-[#e5ded1] p-8 text-left shadow-[0_12px_35px_rgba(55,72,60,.07)] hover:-translate-y-1 transition-transform"><span className={`w-16 h-16 rounded-2xl flex items-center justify-center ${tone}`}><Icon className="w-8 h-8"/></span><h2 className="text-3xl font-bold mt-6">{title}</h2><p className="text-lg text-[#617067] mt-2">{sub}</p></button>)}</div></>}

function GameFrame({title,sub,onRestart,children,done}:{title:string;sub:string;onRestart:()=>void;children:React.ReactNode;done?:boolean}){return <section className="max-w-3xl mx-auto"><div className="text-center py-5"><p className="uppercase tracking-wider text-sm font-bold text-[#c66f2a]">Sunny Games</p><h1 className="text-4xl sm:text-5xl font-bold mt-2">{title}</h1><p className="text-xl text-[#617067] mt-3">{sub}</p></div>{done&&<div role="status" className="mb-5 p-5 rounded-2xl bg-[#e1eddd] text-[#365342] text-xl font-bold text-center"><Check className="inline mr-2"/>Wonderful — you completed it!</div>}<div className="bg-white rounded-[2rem] border border-[#e5ded1] p-5 sm:p-8 shadow-[0_16px_45px_rgba(55,72,60,.08)]">{children}</div><button onClick={onRestart} className="mx-auto mt-5 min-h-14 px-6 rounded-full border-2 border-[#52705b] text-[#405a49] font-bold flex items-center gap-2"><RotateCcw/>Restart</button></section>}

function TilePuzzle(){const solved=[1,2,3,4,5,6,7,8,0],start=[1,2,3,4,0,6,7,5,8];const [tiles,setTiles]=useState(start);const done=tiles.every((v,i)=>v===solved[i]);const move=(i:number)=>{const e=tiles.indexOf(0),near=Math.abs(e-i)===3||(Math.floor(e/3)===Math.floor(i/3)&&Math.abs(e-i)===1);if(!near)return;const n=[...tiles];[n[e],n[i]]=[n[i],n[e]];setTiles(n)};return <GameFrame title="Garden Puzzle" sub="Move a tile into the empty space." done={done} onRestart={()=>setTiles(start)}><div className="grid grid-cols-3 gap-2 max-w-md mx-auto">{tiles.map((v,i)=><button key={i} onClick={()=>move(i)} aria-label={v?`Garden tile ${v}`:"Empty space"} className={`aspect-square rounded-2xl text-3xl font-bold transition-all ${v?"bg-[#eaf1e7] text-[#45614e] border-2 border-[#c9d8c5]":"bg-[#f4efe6]"}`}>{v||""}</button>)}</div></GameFrame>}

function Sudoku(){const solution=[1,2,3,4,3,4,1,2,2,1,4,3,4,3,2,1],fixed=new Set([0,3,5,6,9,10,12,15]);const [values,setValues]=useState(solution.map((v,i)=>fixed.has(i)?v:0));const done=values.every((v,i)=>v===solution[i]);const cycle=(i:number)=>{if(fixed.has(i))return;setValues(a=>a.map((v,j)=>j===i?(v%4)+1:v))};return <GameFrame title="Gentle Sudoku" sub="Tap an empty square to choose 1, 2, 3 or 4." done={done} onRestart={()=>setValues(solution.map((v,i)=>fixed.has(i)?v:0))}><div className="grid grid-cols-4 max-w-md mx-auto border-4 border-[#52705b] rounded-2xl overflow-hidden">{values.map((v,i)=><button key={i} onClick={()=>cycle(i)} className={`aspect-square text-3xl font-bold border border-[#b9c9b7] ${fixed.has(i)?"bg-[#e1eadf] text-[#385042]":"bg-white text-[#d97832]"}`}>{v||""}</button>)}</div></GameFrame>}

const flowers=["🌷","🌻","🌹","🌸"];
function MatchThree(){const initial=[0,1,2,0,2,3,1,2,3,1,3,0,2,1,0,3];const [cells,setCells]=useState(initial);const [selected,setSelected]=useState<number|null>(null);const matched=useMemo(()=>{const s=new Set<number>();for(let r=0;r<4;r++)for(let c=0;c<2;c++){const i=r*4+c;if(cells[i]===cells[i+1]&&cells[i]===cells[i+2])[i,i+1,i+2].forEach(x=>s.add(x))}for(let c=0;c<4;c++)for(let r=0;r<2;r++){const i=r*4+c;if(cells[i]===cells[i+4]&&cells[i]===cells[i+8])[i,i+4,i+8].forEach(x=>s.add(x))}return s},[cells]);const pick=(i:number)=>{if(selected===null)return setSelected(i);const near=Math.abs(selected-i)===4||(Math.floor(selected/4)===Math.floor(i/4)&&Math.abs(selected-i)===1);if(near){const n=[...cells];[n[selected],n[i]]=[n[i],n[selected]];setCells(n)}setSelected(null)};return <GameFrame title="Flower Match" sub="Tap two neighbouring flowers to swap them." done={matched.size>=3} onRestart={()=>{setCells(initial);setSelected(null)}}><div className="grid grid-cols-4 gap-2 max-w-lg mx-auto">{cells.map((v,i)=><button key={i} onClick={()=>pick(i)} className={`aspect-square rounded-2xl text-4xl sm:text-5xl border-2 transition-all ${matched.has(i)?"bg-[#e1eddd] border-[#6f936f]":selected===i?"bg-[#fff1e4] border-[#d97832]":"bg-[#faf7f0] border-[#e5ded1]"}`}>{flowers[v]}</button>)}</div></GameFrame>}

function LinkPairs(){const items=["🐝","🌼","🦋","🍀","🌼","🍀","🐝","🦋"];const [open,setOpen]=useState<number[]>([]),[gone,setGone]=useState<number[]>([]);const choose=(i:number)=>{if(gone.includes(i)||open.includes(i))return;if(open.length===1){const first=open[0];if(items[first]===items[i]){setGone(g=>[...g,first,i]);setOpen([])}else{setOpen([i]);}}else setOpen([i])};return <GameFrame title="Garden Pairs" sub="Choose two matching garden pictures." done={gone.length===items.length} onRestart={()=>{setOpen([]);setGone([])}}><div className="grid grid-cols-4 gap-3 max-w-lg mx-auto">{items.map((v,i)=><button key={i} onClick={()=>choose(i)} disabled={gone.includes(i)} className={`aspect-square rounded-2xl text-4xl sm:text-5xl border-2 ${gone.includes(i)?"bg-[#e1eddd] border-[#8aaa85] opacity-40":open.includes(i)?"bg-[#fff1e4] border-[#d97832]":"bg-[#52705b] border-[#405a49]"}`}>{gone.includes(i)||open.includes(i)?v:"?"}</button>)}</div></GameFrame>}
