import React, { useMemo, useState } from "react";
import { ArrowLeft, Check, Grid3X3, Link2, Puzzle, RotateCcw, Sparkles } from "lucide-react";

type Game="hub"|"puzzle"|"sudoku"|"match3"|"links";
const games=[
  {id:"puzzle" as Game,title:"Garden Puzzle",sub:"Put the garden picture back in order.",icon:Puzzle,tone:"bg-[#fff1e4] text-[#c66f2a]"},
  {id:"sudoku" as Game,title:"Gentle Sudoku",sub:"A calm 4 × 4 number puzzle.",icon:Grid3X3,tone:"bg-[#eaf1e7] text-[#52705b]"},
  {id:"match3" as Game,title:"Flower Match",sub:"Match three flowers in a row.",icon:Sparkles,tone:"bg-[#fff1e4] text-[#c66f2a]"},
  {id:"links" as Game,title:"Garden Pairs",sub:"Find and connect matching garden symbols.",icon:Link2,tone:"bg-[#eaf1e7] text-[#52705b]"},
];

export function LeisureGames({initial="hub",onExit}:{initial?:Game;onExit:()=>void}){const [game,setGame]=useState<Game>(initial);return <div className="min-h-screen bg-[radial-gradient(circle_at_70%_0%,#fff7df_0%,#f8efe3_38%,#edf3e9_100%)] text-[#3b2519]"><header className="max-w-6xl mx-auto p-5 flex items-center justify-between"><button onClick={game==="hub"?onExit:()=>setGame("hub")} className="min-h-14 px-5 rounded-full bg-white/80 backdrop-blur border border-white shadow-sm font-bold flex items-center gap-2"><ArrowLeft/>{game==="hub"?"Back to Sunny":"All games"}</button><div className="px-5 py-3 rounded-full bg-white/80 shadow-sm font-bold">Mary⌄</div></header><main className="max-w-6xl mx-auto px-5 pb-16">{game==="hub"?<Hub onPick={setGame}/>:game==="puzzle"?<TilePuzzle/>:game==="sudoku"?<Sudoku/>:game==="match3"?<MatchThree/>:<LinkPairs/>}</main></div>}

function Hub({onPick}:{onPick:(g:Game)=>void}){return <><section className="relative overflow-hidden rounded-[2.5rem] bg-white/65 backdrop-blur-xl border border-white shadow-[0_24px_70px_rgba(111,76,46,.12)] p-8 sm:p-12 mb-7"><div className="max-w-2xl"><p className="uppercase tracking-[.22em] text-sm font-bold text-[#ed7639]">Sunny Games</p><h1 className="text-4xl sm:text-6xl font-bold mt-3">Good morning, Mary!</h1><p className="text-xl text-[#705f54] mt-4 leading-relaxed">Let’s play something gentle together. There is no timer, so you can enjoy every moment.</p></div><div className="sunny-breathe mt-8 sm:mt-0 sm:absolute sm:right-14 sm:top-1/2 sm:-translate-y-1/2 w-28 h-28 rounded-full bg-gradient-to-br from-[#ffc84b] to-[#f58b37] shadow-[0_20px_45px_rgba(238,136,43,.3)] flex items-center justify-center text-6xl" aria-label="Sunny waving">☀️</div></section><div className="flex items-end justify-between mb-5"><div><p className="font-bold text-[#ed7639]">CHOOSE A GAME</p><h2 className="text-3xl sm:text-4xl font-bold">Today’s activities</h2></div><p className="hidden sm:block text-[#75685e]">Large, calm and easy to play</p></div><div className="grid sm:grid-cols-2 gap-5">{games.map(({id,title,sub,icon:Icon},index)=><button key={id} onClick={()=>onPick(id)} className="group overflow-hidden min-h-60 bg-white/85 rounded-[2rem] border border-white p-0 text-left shadow-[0_16px_45px_rgba(91,65,43,.10)] hover:-translate-y-1 hover:shadow-[0_22px_55px_rgba(91,65,43,.16)] transition-all"><div className={`h-28 flex items-center justify-center text-6xl ${index%2?"bg-gradient-to-br from-[#e3eddc] to-[#f4f7ed]":"bg-gradient-to-br from-[#ffe2c9] to-[#fff5e9]"}`}>{index===0?"🧩":index===1?"🔢":index===2?"🌸":"🦋"}</div><div className="p-6 flex gap-4"><span className={`w-12 h-12 shrink-0 rounded-2xl flex items-center justify-center ${index%2?"bg-[#e5efdf] text-[#52705b]":"bg-[#fff0e4] text-[#e06f36]"}`}><Icon/></span><div><h3 className="text-2xl font-bold group-hover:text-[#df6f37] transition-colors">{title}</h3><p className="text-base text-[#70675f] mt-1">{sub}</p><span className="inline-block mt-3 font-bold text-[#df6f37]">Play now →</span></div></div></button>)}</div></>}

function GameFrame({title,sub,onRestart,children,done}:{title:string;sub:string;onRestart:()=>void;children:React.ReactNode;done?:boolean}){return <section className="max-w-3xl mx-auto"><div className="text-center py-5"><div className="w-20 h-20 mx-auto rounded-full bg-gradient-to-br from-[#ffc84b] to-[#f58b37] shadow-lg flex items-center justify-center text-4xl">☀️</div><p className="uppercase tracking-wider text-sm font-bold text-[#e67639] mt-4">Playing with Sunny</p><h1 className="text-4xl sm:text-5xl font-bold mt-2">{title}</h1><p className="text-xl text-[#75685e] mt-3">{sub}</p></div>{done&&<div role="status" className="mb-5 p-5 rounded-2xl bg-[#e1eddd] text-[#365342] text-xl font-bold text-center"><Check className="inline mr-2"/>Wonderful — you completed it!</div>}<div className="bg-white/85 backdrop-blur rounded-[2.5rem] border border-white p-5 sm:p-9 shadow-[0_20px_60px_rgba(91,65,43,.12)]">{children}</div><button onClick={onRestart} className="mx-auto mt-5 min-h-14 px-6 rounded-full bg-white/80 border-2 border-[#52705b] text-[#405a49] font-bold flex items-center gap-2"><RotateCcw/>Restart</button></section>}

function TilePuzzle(){const solved=[1,2,3,4,5,6,7,8,0],start=[1,2,3,4,0,6,7,5,8];const [tiles,setTiles]=useState(start);const done=tiles.every((v,i)=>v===solved[i]);const move=(i:number)=>{const e=tiles.indexOf(0),near=Math.abs(e-i)===3||(Math.floor(e/3)===Math.floor(i/3)&&Math.abs(e-i)===1);if(!near)return;const n=[...tiles];[n[e],n[i]]=[n[i],n[e]];setTiles(n)};return <GameFrame title="Garden Puzzle" sub="Move a tile into the empty space." done={done} onRestart={()=>setTiles(start)}><div className="grid grid-cols-3 gap-2 max-w-md mx-auto">{tiles.map((v,i)=><button key={i} onClick={()=>move(i)} aria-label={v?`Garden tile ${v}`:"Empty space"} className={`aspect-square rounded-2xl text-3xl font-bold transition-all ${v?"bg-[#eaf1e7] text-[#45614e] border-2 border-[#c9d8c5]":"bg-[#f4efe6]"}`}>{v||""}</button>)}</div></GameFrame>}

function Sudoku(){const solution=[1,2,3,4,3,4,1,2,2,1,4,3,4,3,2,1],fixed=new Set([0,3,5,6,9,10,12,15]);const [values,setValues]=useState(solution.map((v,i)=>fixed.has(i)?v:0));const done=values.every((v,i)=>v===solution[i]);const cycle=(i:number)=>{if(fixed.has(i))return;setValues(a=>a.map((v,j)=>j===i?(v%4)+1:v))};return <GameFrame title="Gentle Sudoku" sub="Tap an empty square to choose 1, 2, 3 or 4." done={done} onRestart={()=>setValues(solution.map((v,i)=>fixed.has(i)?v:0))}><div className="grid grid-cols-4 max-w-md mx-auto border-4 border-[#52705b] rounded-2xl overflow-hidden">{values.map((v,i)=><button key={i} onClick={()=>cycle(i)} className={`aspect-square text-3xl font-bold border border-[#b9c9b7] ${fixed.has(i)?"bg-[#e1eadf] text-[#385042]":"bg-white text-[#d97832]"}`}>{v||""}</button>)}</div></GameFrame>}

const flowers=["🌷","🌻","🌹","🌸"];
function MatchThree(){const initial=[0,1,2,0,2,3,1,2,3,1,3,0,2,1,0,3];const [cells,setCells]=useState(initial);const [selected,setSelected]=useState<number|null>(null);const matched=useMemo(()=>{const s=new Set<number>();for(let r=0;r<4;r++)for(let c=0;c<2;c++){const i=r*4+c;if(cells[i]===cells[i+1]&&cells[i]===cells[i+2])[i,i+1,i+2].forEach(x=>s.add(x))}for(let c=0;c<4;c++)for(let r=0;r<2;r++){const i=r*4+c;if(cells[i]===cells[i+4]&&cells[i]===cells[i+8])[i,i+4,i+8].forEach(x=>s.add(x))}return s},[cells]);const pick=(i:number)=>{if(selected===null)return setSelected(i);const near=Math.abs(selected-i)===4||(Math.floor(selected/4)===Math.floor(i/4)&&Math.abs(selected-i)===1);if(near){const n=[...cells];[n[selected],n[i]]=[n[i],n[selected]];setCells(n)}setSelected(null)};return <GameFrame title="Flower Match" sub="Tap two neighbouring flowers to swap them." done={matched.size>=3} onRestart={()=>{setCells(initial);setSelected(null)}}><div className="grid grid-cols-4 gap-2 max-w-lg mx-auto">{cells.map((v,i)=><button key={i} onClick={()=>pick(i)} className={`aspect-square rounded-2xl text-4xl sm:text-5xl border-2 transition-all ${matched.has(i)?"bg-[#e1eddd] border-[#6f936f]":selected===i?"bg-[#fff1e4] border-[#d97832]":"bg-[#faf7f0] border-[#e5ded1]"}`}>{flowers[v]}</button>)}</div></GameFrame>}

function LinkPairs(){const items=["🐝","🌼","🦋","🍀","🌼","🍀","🐝","🦋"];const [open,setOpen]=useState<number[]>([]),[gone,setGone]=useState<number[]>([]);const choose=(i:number)=>{if(gone.includes(i)||open.includes(i))return;if(open.length===1){const first=open[0];if(items[first]===items[i]){setGone(g=>[...g,first,i]);setOpen([])}else{setOpen([i]);}}else setOpen([i])};return <GameFrame title="Garden Pairs" sub="Choose two matching garden pictures." done={gone.length===items.length} onRestart={()=>{setOpen([]);setGone([])}}><div className="grid grid-cols-4 gap-3 max-w-lg mx-auto">{items.map((v,i)=><button key={i} onClick={()=>choose(i)} disabled={gone.includes(i)} className={`aspect-square rounded-2xl text-4xl sm:text-5xl border-2 ${gone.includes(i)?"bg-[#e1eddd] border-[#8aaa85] opacity-40":open.includes(i)?"bg-[#fff1e4] border-[#d97832]":"bg-[#52705b] border-[#405a49]"}`}>{gone.includes(i)||open.includes(i)?v:"?"}</button>)}</div></GameFrame>}
