import React, { useState } from "react";
import { BookHeart, Check, Edit3, Share2, Sparkles, Trash2 } from "lucide-react";
import { buildFamilyWeeklySummary, buildRecommendations, generateStory, type ResidentMemoryJournal, type ResidentPreference, type ResidentRecommendation } from "../lib/residentPersonalisation";
import type { CompanionSession } from "../lib/residentCompanion";

export const MEMORY_PROMPTS = ["Tell me about your childhood.", "Tell me about your favourite flower.", "Tell me about your first job.", "Tell me about your happiest memory.", "Tell me about someone you love.", "Tell me about a garden you remember."];

export function Recommendations({ profile, onAction }: { profile: ResidentPreference; onAction: (action: ResidentRecommendation["action"]) => void }) {
  return <section className="mt-10"><h2 className="text-3xl font-bold mb-2">Today's Recommendations</h2><p className="text-lg text-slate-600 mb-5">These are optional. Choose anything you may enjoy.</p><div className="grid md:grid-cols-3 gap-4">{buildRecommendations(profile).map(item => <button key={item.id} onClick={() => onAction(item.action)} className="min-h-40 rounded-3xl bg-white border-2 border-orange-200 p-5 text-left"><Sparkles className="w-8 h-8 text-orange-500 mb-4"/><strong className="block text-xl mb-2">{item.title}</strong><span className="text-base text-slate-600">{item.reason}</span></button>)}</div></section>;
}

export function MemoryJournal({ language, profile, session, onChange, onTalk }: { language: "en" | "zh"; profile: ResidentPreference; session: CompanionSession; onChange: (profile: ResidentPreference) => void; onTalk: (prompt: string) => void }) {
  const [draft, setDraft] = useState<ResidentMemoryJournal | null>(null);
  const [consentId, setConsentId] = useState<string | null>(null);
  const createDraft = () => setDraft(generateStory(session.messages.filter(message => message.role === "resident").map(message => message.text), "Memory Journal", language));
  const save = () => { if (!draft) return; onChange({ ...profile, savedMemories: [...profile.savedMemories.filter(item => item.id !== draft.id), draft] }); setDraft(null); };
  const remove = (id: string) => onChange({ ...profile, savedMemories: profile.savedMemories.filter(item => item.id !== id) });
  const share = (id: string) => { onChange({ ...profile, savedMemories: profile.savedMemories.map(item => item.id === id ? { ...item, sharedWithFamily: true } : item) }); setConsentId(null); };
  return <section className="max-w-4xl mx-auto"><h1 className="text-4xl sm:text-5xl font-bold mb-3">Share a Memory</h1><p className="text-xl text-slate-600 mb-6">Choose one idea, or tell Sunny anything you remember. Sunny asks one question at a time.</p><div className="grid sm:grid-cols-2 gap-3">{MEMORY_PROMPTS.map(prompt => <button key={prompt} onClick={() => onTalk(prompt)} className="min-h-24 rounded-2xl bg-white border-2 border-orange-200 p-4 text-left text-xl font-bold">{prompt}</button>)}</div><button onClick={createDraft} className="w-full min-h-16 mt-6 rounded-2xl bg-orange-500 text-white text-xl font-bold flex items-center justify-center gap-2"><BookHeart/>Create a story draft from my conversation</button>
    {draft && <article className="mt-6 bg-[#fff0cf] border-2 border-[#e3c06e] rounded-3xl p-6"><label className="block text-xl font-bold mb-2">Edit story title<input value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })} className="block w-full min-h-14 mt-2 bg-white border-2 border-orange-200 rounded-xl px-4"/></label><label className="block text-xl font-bold mt-4">Edit story<textarea value={draft.body} onChange={event => setDraft({ ...draft, body: event.target.value })} rows={5} className="block w-full mt-2 bg-white border-2 border-orange-200 rounded-xl p-4 font-normal"/></label><div className="flex gap-3 mt-4"><button onClick={save} className="min-h-14 flex-1 bg-[#45634f] text-white rounded-xl text-lg font-bold"><Check className="inline mr-2"/>Save Story</button><button onClick={() => setDraft(null)} className="min-h-14 flex-1 bg-white border-2 border-orange-300 rounded-xl text-lg font-bold">Cancel</button></div></article>}
    {profile.savedMemories.length > 0 && <div className="mt-8"><h2 className="text-3xl font-bold mb-4">Mary's Memory Journal</h2>{profile.savedMemories.map(memory => <article key={memory.id} className="bg-white border-2 border-orange-100 rounded-3xl p-6 mb-4"><h3 className="text-2xl font-bold mb-2">{memory.title}</h3><p className="text-xl leading-relaxed mb-4">{memory.body}</p><div className="flex flex-wrap gap-2"><button onClick={() => setDraft(memory)} className="min-h-12 px-4 rounded-xl border-2 border-orange-200"><Edit3 className="inline mr-2"/>Edit</button><button onClick={() => remove(memory.id)} className="min-h-12 px-4 rounded-xl border-2 border-red-200 text-red-800"><Trash2 className="inline mr-2"/>Delete</button>{memory.sharedWithFamily ? <span className="min-h-12 px-4 rounded-xl bg-green-100 text-green-800 flex items-center"><Check className="mr-2"/>Shared with permission</span> : <button onClick={() => setConsentId(memory.id)} className="min-h-12 px-4 rounded-xl bg-[#45634f] text-white"><Share2 className="inline mr-2"/>Share with Family</button>}</div>{consentId === memory.id && <div role="alertdialog" className="mt-4 p-4 rounded-2xl bg-amber-50 border-2 border-amber-400"><p className="text-lg font-bold mb-3">Do you give permission to share this story with your family?</p><div className="flex gap-2"><button onClick={() => share(memory.id)} className="min-h-12 px-5 bg-green-700 text-white rounded-xl font-bold">Yes, share it</button><button onClick={() => setConsentId(null)} className="min-h-12 px-5 bg-white border-2 border-amber-300 rounded-xl font-bold">No, keep private</button></div></div>}</article>)}</div>}
    <article className="mt-8 bg-[#fff0e0] rounded-3xl p-6 border-2 border-orange-200 whitespace-pre-line"><h2 className="text-2xl font-bold mb-3">Family Weekly Summary (demo)</h2><p className="text-lg leading-relaxed">{buildFamilyWeeklySummary(profile, session)}</p></article>
  </section>;
}
